backend:
  name: github
  repo: inspireambitions/sauditravelandleisure.com
  branch: main
  base_url: https://sauditravelandleisure.com
  auth_endpoint: /auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "/"
    create: true
    slug: "{{slug}}"
    extension: "html"
    summary: "{{filename}}"
    fields:
      - {label: "Body", name: "body", widget: "text"}
