backend:
  name: github
  repo: inspireambitions/sauditravelandleisure.com
  branch: main
  auth_type: pkce
  app_id: sauditravelandleisure-cms

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "/"
    create: true
    slug: "{{slug}}"
    extension: "html"
    format: "raw"
    summary: "{{filename}}"
    filter: {field: "filename", pattern: "^(?!admin|about|contact|404|index|page|sitemap|robots)"}
    fields:
      - {label: "Body", name: "body", widget: "code", default_language: "html"}
